apiVersion: v1
kind: Pod
metadata:
  labels:
    run: k8s-host
  name: k8s-host
spec:
  containers:
  - command:
      - sleep
      - "3600"
    image: alpine
    imagePullPolicy: IfNotPresent
    name: k8s-host
    securityContext:
      privileged: true
  hostPID: true
