apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu-nonroot
  name: ubuntu-nonroot
spec:
  containers:
  - image: ubuntu:24.04
    name: ubuntu-nonroot
    command:
      - sleep
      - "12000"
    securityContext:
      runAsNonRoot: true
      runAsUser: 10000
    volumeMounts:
      - name: host
        mountPath: /host
  volumes:
    - name: host
      hostPath:
        path: /
        type: Directory
