apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu-hostpid
  name: ubuntu-hostpid
spec:
  containers:
  - image: ubuntu:24.04
    name: ubuntu-hostpid
    command:
      - sleep
      - "12000"
  hostPID: true
