apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu-priv
  name: ubuntu-priv
spec:
  containers:
  - image: ubuntu:24.04
    name: ubuntu-priv
    command:
      - sleep
      - "36000"
    securityContext:
      privileged: true
  hostPID: true
